### ISSUE TITLE
UnitsTypeCV API Call Gives 500 Error

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2ControlledVocabularies#17] opened 2015-10-04 06:40 UTC
When I try to get the UnitsTypeCV terms via the API, I get a 500 error.  For example:

http://vocabulary.odm2.org/api/v1/unitstype/?format=skos

This is affecting my ability to update my Little Bear River data use case.  The Python script to automatically populate the CV tables in a blank ODM2 database obviously isn't loading the UnitsTypeCV terms.  As an aside, the CV Loader Python script doesn't throw an error either that the web service call failed, so it took me a bit to figure out that it really wasn't a problem with the script, but rather the web service call was failing.

**Comment by denvaar** [comment] 2015-10-07 00:41
This was apparently caused by some 'test' requests that were missing some data. There are some inconsistencies in the database between the cv table and the cv request table which is causing the serialization to fail.

***I have updated the server so that it should work***, however I am not going to close this issue until I am certain that we have the correct null/not null settings on each field.

**Comment by horsburgh** [comment] 2015-10-07 01:37
The required fields in the above are correct, and it seems to be working on the server, so @denvaar - close this one when you feel its done.

**Comment by denvaar** [comment] 2015-10-08 18:22
Closing issue. I wrote a script to modify all of the tables with correct null/not null values (name required, definition not required.) Also updated web app to correctly reflect the changes.

**Closed by denvaar** 2015-10-08 18:22 UTC
Labels: bug, help wanted
